"""Action parser for SENTINEL LLM agent.

Extracts a valid Action dict from LLM free-text output.  The model is prompted
to think first (<think>…</think>) then emit a JSON code block.  This module:

  1. Strips the <think>…</think> scratchpad
  2. Extracts the first ```json … ``` code block (or raw JSON object)
  3. Validates required keys: agent, category, name, params
  4. Falls back to a safe UCB1+heuristic action on any parse failure

Design goals:
  - Never raise an exception (always returns a valid action)
  - Log all parse failures for offline debugging
  - Accept partial JSON (missing params → empty dict)
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Valid action registry (for validation)
# ---------------------------------------------------------------------------

_VALID_AGENTS: frozenset[str] = frozenset(
    ["holmes", "forge", "argus", "hermes", "oracle"]
)

_VALID_CATEGORIES: frozenset[str] = frozenset(
    ["investigative", "remediation", "deployment", "meta"]
)

_INVESTIGATIVE_ACTIONS: frozenset[str] = frozenset([
    "QueryLogs", "QueryMetrics", "QueryTrace", "QueryTraces", "CheckDependencies",
    "FormHypothesis", "AnomalyDetect",
])

_REMEDIATION_ACTIONS: frozenset[str] = frozenset([
    "RestartService", "ScaleService", "ModifyConfig", "RollbackDeployment",
    "DrainTraffic", "ModifyRateLimit",
])

_DEPLOYMENT_ACTIONS: frozenset[str] = frozenset([
    "CanaryDeploy", "FullDeploy", "Rollback",
])

_META_ACTIONS: frozenset[str] = frozenset([
    "CloseIncident", "EscalateToHuman", "GenerateNewScenario",
])

_ALL_ACTIONS: frozenset[str] = (
    _INVESTIGATIVE_ACTIONS | _REMEDIATION_ACTIONS | _DEPLOYMENT_ACTIONS | _META_ACTIONS
)

# category → allowed actions
_CATEGORY_ACTIONS: dict[str, frozenset[str]] = {
    "investigative": _INVESTIGATIVE_ACTIONS,
    "remediation":   _REMEDIATION_ACTIONS,
    "deployment":    _DEPLOYMENT_ACTIONS,
    "meta":          _META_ACTIONS,
}

# agent → default category
_AGENT_CATEGORY: dict[str, str] = {
    "holmes": "investigative",
    "argus":  "investigative",
    "forge":  "remediation",
    "oracle": "meta",
    "hermes": "deployment",
}

# ---------------------------------------------------------------------------
# Regex patterns
# ---------------------------------------------------------------------------

# Matches ```json ... ``` or ``` ... ```
_CODE_BLOCK_RE = re.compile(
    r"```(?:json)?\s*([\s\S]*?)```", re.IGNORECASE
)

# Matches the outermost JSON object {...}
_JSON_OBJECT_RE = re.compile(r"\{[\s\S]*\}", re.DOTALL)

# Matches <think>...</think> scratchpad
_THINK_RE = re.compile(r"<think>[\s\S]*?</think>", re.IGNORECASE)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse_llm_action(
    llm_output: str,
    fallback_agent: str = "holmes",
) -> dict[str, Any]:
    """Extract and validate an action dict from raw LLM output text.

    Args:
        llm_output: The raw string generated by the LLM.
        fallback_agent: Agent role to use when parse fails.

    Returns:
        A valid action dict with keys: agent, category, name, params.
        Never raises — falls back to a safe QueryLogs action on failure.
    """
    # 1. Strip <think> scratchpad
    cleaned = _THINK_RE.sub("", llm_output).strip()

    # 2. Try extracting JSON from code block
    action = _extract_from_code_block(cleaned)

    # 3. Fall back to raw JSON object extraction
    if action is None:
        action = _extract_raw_json(cleaned)

    # 4. Fall back to safe default
    if action is None:
        logger.warning(
            "parse_llm_action: could not extract JSON from output (len=%d). "
            "Falling back to QueryLogs.",
            len(llm_output),
        )
        return _safe_fallback(fallback_agent)

    # 5. Validate and repair
    return _validate_and_repair(action, fallback_agent)


def strip_think(text: str) -> str:
    """Return LLM output with <think>…</think> block removed."""
    return _THINK_RE.sub("", text).strip()


def extract_think(text: str) -> str:
    """Return only the content inside <think>…</think>, or empty string."""
    m = re.search(r"<think>([\s\S]*?)</think>", text, re.IGNORECASE)
    return m.group(1).strip() if m else ""


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _extract_from_code_block(text: str) -> dict | None:
    """Extract first JSON code block and parse it."""
    m = _CODE_BLOCK_RE.search(text)
    if not m:
        return None
    return _try_parse(m.group(1).strip())


def _extract_raw_json(text: str) -> dict | None:
    """Find and parse the first raw JSON object in the text."""
    m = _JSON_OBJECT_RE.search(text)
    if not m:
        return None
    return _try_parse(m.group(0))


def _try_parse(s: str) -> dict | None:
    """Try JSON parsing; return None on failure."""
    try:
        obj = json.loads(s)
        if isinstance(obj, dict):
            return obj
    except (json.JSONDecodeError, ValueError):
        pass
    return None


def _validate_and_repair(action: dict, fallback_agent: str) -> dict:
    """Validate action keys and repair where possible."""
    # Ensure required keys exist
    agent = action.get("agent", fallback_agent)
    if agent not in _VALID_AGENTS:
        logger.debug("Unknown agent '%s' → using '%s'", agent, fallback_agent)
        agent = fallback_agent

    name = action.get("name", "")
    if name not in _ALL_ACTIONS:
        # Try case-insensitive match
        name_lower = name.lower()
        matched = next((a for a in _ALL_ACTIONS if a.lower() == name_lower), None)
        if matched:
            name = matched
        else:
            logger.debug("Unknown action name '%s' → QueryLogs", name)
            name = "QueryLogs"

    # Infer category from action name
    category = action.get("category", "")
    if category not in _VALID_CATEGORIES:
        category = _infer_category(name)

    # Ensure category ↔ action name consistency
    if name not in _CATEGORY_ACTIONS.get(category, frozenset()):
        category = _infer_category(name)

    # Ensure params is a dict
    params = action.get("params", {})
    if not isinstance(params, dict):
        params = {}

    # Ensure agent ↔ category consistency (soft check, not enforced)
    expected_cat = _AGENT_CATEGORY.get(agent, "investigative")
    if category != expected_cat:
        logger.debug(
            "Agent '%s' issued '%s' action (expected category '%s' → got '%s')",
            agent, name, expected_cat, category,
        )

    return {
        "agent":    agent,
        "category": category,
        "name":     name,
        "params":   params,
    }


def _infer_category(name: str) -> str:
    """Infer action category from action name."""
    if name in _INVESTIGATIVE_ACTIONS:
        return "investigative"
    if name in _REMEDIATION_ACTIONS:
        return "remediation"
    if name in _DEPLOYMENT_ACTIONS:
        return "deployment"
    return "meta"


def _safe_fallback(agent: str) -> dict:
    """Return the safest possible action for the given agent."""
    if agent == "forge":
        return {
            "agent":    "forge",
            "category": "remediation",
            "name":     "ScaleService",
            "params":   {"service": "api-gateway", "replicas": 2},
        }
    if agent == "hermes":
        return {
            "agent":    "hermes",
            "category": "meta",
            "name":     "EscalateToHuman",
            "params":   {"reason": "LLM parse failure — escalating for safety"},
        }
    if agent == "oracle":
        return {
            "agent":    "oracle",
            "category": "meta",
            "name":     "EscalateToHuman",
            "params":   {"reason": "LLM parse failure — escalating for safety"},
        }
    # Default: HOLMES investigates
    return {
        "agent":    "holmes",
        "category": "investigative",
        "name":     "QueryLogs",
        "params":   {"service": "api-gateway", "time_range": [0, 300]},
    }
